# Site
name: "Nasir Khan Saikat"
title: "Nasir Khan Saikat"
description: "Nasir Khan Saikat - Full Stack Developer, Photographer & Author"
logo: 'assets/images/nasir-khan-saikat-logo.png'
favicon: 'assets/images/logo.png'
baseurl: 'https://nasirkhan.github.io/nasir-khan-saikat-2'
google_analytics: 'UA-xxxxxxxx-1'
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
email: nasir8891@gmail.com

# Authors
authors:
  nasirkhan:
    name: nasirkhan
    display_name: 'Nasir Khan Saikat'
    gravatar: 96bf4c3a8875db84432298eba29efbc8
    email: nasir8891@gmail.com
    web: https://nasirkhn.com
    twitter: https://twitter.com/nasir8891
    description: "Nasir Khan Saikat - Full Stack Developer, Photographer & Author"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: rouge
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
